DROP TABLE IF EXISTS SM_STADIUM;
CREATE TABLE SM_STADIUM
(
    STADIUM_ID LONG,
    CREATED_AT TIMESTAMP,
    CREATED_BY VARCHAR,
    UPDATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR,
    STADIUM_ADDRESS VARCHAR,
    STADIUM_MAXIMUM_PEOPLE INT,
    STADIUM_MINIMUM_PEOPLE INT,
    STADIUM_NAME VARCHAR,
    STADIUM_SIZE INT
);